image: docker:18

variables:
  GIT_SSL_NO_VERIFY: 1
  DOCKER_DRIVER: overlay2
  REPOSITORY_HOST: 830055101690.dkr.ecr.us-west-2.amazonaws.com
  REPOSITORY_IMAGE: metal/proton-market
  SERVICE_NAME: proton-market

stages:
  - build
  - release

build development:
  stage: build
  only:
    - develop@proton/proton-market
  services:
    - docker:dind
  before_script:
    - docker info
    - apk add --no-cache curl jq python py-pip
    - pip install awscli yq
  script:
    - export IMAGE=devel-$CI_COMMIT_SHA
    - $(aws ecr get-login --no-include-email --region us-west-2)
    - docker build --no-cache --build-arg NPM_TOKEN=${NPM_TOKEN} -t $REPOSITORY_IMAGE .
    - docker tag $REPOSITORY_IMAGE:latest $REPOSITORY_HOST/$REPOSITORY_IMAGE:latest
    - docker tag $REPOSITORY_IMAGE:latest $REPOSITORY_HOST/$REPOSITORY_IMAGE:$IMAGE
    - docker push $REPOSITORY_HOST/$REPOSITORY_IMAGE:latest
    - docker push $REPOSITORY_HOST/$REPOSITORY_IMAGE:$IMAGE

update development helm chart:
  image: 830055101690.dkr.ecr.us-west-2.amazonaws.com/metal/ci:latest
  stage: release
  only:
    - develop@proton/proton-market
  script:
    - export IMAGE=devel-$CI_COMMIT_SHA
    - git clone -b develop git@ci.metalpay.network:metalpay/metal-devops.git
    - cd metal-devops/helm/proton
    - touch values-development.yaml
    - cat values-development.yaml | yq '."'$SERVICE_NAME'".image.tag="'$IMAGE'"' -y > new-values.yaml
    - mv -f new-values.yaml values-development.yaml
    - git add values-development.yaml
    - if [[ -z $(git status -s) ]]; then echo 'Tree is clean'; else git commit -m "Update $SERVICE_NAME image tag to $IMAGE"; git push; fi